deployment:
    tasks:
          - export DEPLOYPATH=../../test-front/
          # - npm install
          # - npm run build
          - /bin/cp -R dist/* $DEPLOYPATH
        # - composer install --ignore-platform-reqs --optimize-autoloader --no-progress
        # - cp -n .env.example .env
        # - mv public_html public_html_old
        # - ln -s /home/user/qaqc-backend.marketsquareng.com/public /home/user/qaqc-backend.marketsquareng.com

